from django.db import models

class Product(models.Model):
    CATEGORY_CHOICES = [
        ("fruits", "Fruits"),
        ("vegetables", "Vegetables"),
        ("dairy", "Dairy"),
        ("bakery", "Bakery"),
        ("snacks", "Snacks"),
        ("beverages", "Beverages"),
        ("household", "Household"),
        ("meat", "Meat"),
        ("seafood", "Seafood"),
        ("frozen", "Frozen"),
        ("canned_goods", "Canned Goods"),
        ("condiments", "Condiments"),
        ("spices", "Spices"),
        ("grains", "Grains"),
        ("rice", "Rice"),
        ("pasta", "Pasta"),
        ("breakfast", "Breakfast"),
        ("cereals", "Cereals"),
        ("baking", "Baking"),
        ("sugar_and_sweeteners", "Sugar & Sweeteners"),
        ("oils_and_vinegars", "Oils & Vinegars"),
        ("baby", "Baby"),
        ("pet_food", "Pet Food"),
        ("personal_care", "Personal Care"),
        ("health_and_wellness", "Health & Wellness"),
        ("organic", "Organic"),
        ("gluten_free", "Gluten Free"),
        ("vegan", "Vegan"),
        ("vegetarian", "Vegetarian"),
        ("asian_foods", "Asian Foods"),
        ("italian_foods", "Italian Foods"),
        ("mexican_foods", "Mexican Foods"),
        ("indian_foods", "Indian Foods"),
        ("middle_eastern_foods", "Middle Eastern Foods"),
        ("mediterranean_foods", "Mediterranean Foods"),
        ("chinese_foods", "Chinese Foods"),
        ("japanese_foods", "Japanese Foods"),
        ("korean_foods", "Korean Foods"),
        ("thai_foods", "Thai Foods"),
        ("vietnamese_foods", "Vietnamese Foods"),
        ("french_foods", "French Foods"),
        ("beverages_alcoholic", "Alcoholic Beverages"),
        ("beer", "Beer"),
        ("wine", "Wine"),
        ("spirits", "Spirits"),
        ("ready_meals", "Ready Meals"),
        ("deli", "Deli"),
        ("cheese", "Cheese"),
        ("eggs", "Eggs"),
        ("tofu_and_plant_protein", "Tofu & Plant Protein"),
        ("nuts_and_seeds", "Nuts & Seeds"),
        ("dried_fruit", "Dried Fruit"),
        ("herbs", "Herbs"),
        ("salad_and_greens", "Salad & Greens"),
        ("spreads_and_tubs", "Spreads & Tubs"),
        ("sauces", "Sauces"),
        ("soups", "Soups"),
        ("broths", "Broths"),
        ("marinades", "Marinades"),
        ("grilling", "Grilling"),
        ("barbecue", "Barbecue"),
        ("party_food", "Party Food"),
        ("ice_cream", "Ice Cream"),
        ("desserts", "Desserts"),
        ("chocolates", "Chocolates"),
        ("confectionery", "Confectionery"),
        ("tea", "Tea"),
        ("coffee", "Coffee"),
        ("juices", "Juices"),
        ("smoothies", "Smoothies"),
        ("sports_and_energy", "Sports & Energy"),
        ("nutritional_supplements", "Nutritional Supplements"),
        ("breakfast_bars", "Breakfast Bars"),
        ("baby_care", "Baby Care"),
        ("diapers", "Diapers"),
        ("feminine_hygiene", "Feminine Hygiene"),
        ("cleaning_supplies", "Cleaning Supplies"),
        ("laundry", "Laundry"),
        ("kitchenware", "Kitchenware"),
        ("storage_and_wraps", "Storage & Wraps"),
        ("paper_products", "Paper Products"),
        ("batteries_and_lightbulbs", "Batteries & Lightbulbs"),
        ("electronics_accessories", "Electronics Accessories"),
        ("office_supplies", "Office Supplies"),
        ("seasonal", "Seasonal"),
        ("holiday", "Holiday"),
        ("gifts_and_baskets", "Gifts & Baskets"),
        ("flowers", "Flowers"),
        ("garden", "Garden"),
        ("grains_and_cereals", "Grains & Cereals"),
        ("health_foods", "Health Foods"),
        ("low_sodium", "Low Sodium"),
        ("low_sugar", "Low Sugar"),
        ("keto", "Keto"),
        ("paleo", "Paleo"),
        ("ready_to_cook", "Ready to Cook"),
        ("meal_kits", "Meal Kits"),
        ("instant_foods", "Instant Foods"),
        ("pantry_essentials", "Pantry Essentials"),
        ("specialty_diet", "Specialty Diet"),
        ("international_fusion", "International Fusion"),
        ("ethnic_specialties", "Ethnic Specialties"),
        ("bulk_items", "Bulk Items"),
        ("wholesale", "Wholesale"),
        ("party_supplies", "Party Supplies"),
        ("baby_food", "Baby Food"),
        ("toddler_snacks", "Toddler Snacks"),
        ("organic_produce", "Organic Produce"),
        ("gourmet", "Gourmet"),
        ("imported", "Imported")
    ]
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)
    image_url = models.URLField(blank=True, null=True)
    image = models.ImageField(upload_to='products/', blank=True, null=True)

    sold_count = models.PositiveIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name
